version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Warsaw"
    labels:
      - "dependencies"
      - "ci"
    assignees:
      - "yachiko"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
