# This file was generated by GoReleaser. DO NOT EDIT.
cask "clerk" do
  version "0.0.6"

  on_macos do
    on_arm do
      sha256 "1f973d4841c03832e126c4431d75552f9d0f3488f64878031121395793c7cb97"
      url "https://github.com/yachiko/clerk/releases/download/v#{version}/clerk_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9bc209d007abad600fa2818746b8955c882012d2d827ed106caa0305f7f2cbc8"
      url "https://github.com/yachiko/clerk/releases/download/v#{version}/clerk_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3f288659d726107661defff59b7287fdb750fe5d5d554662e2bdd72cc010417"
      url "https://github.com/yachiko/clerk/releases/download/v#{version}/clerk_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c1b7351dcf1d3b21ce48c64a769af3b580d417cdef428b3b4d0a97b577d55833"
      url "https://github.com/yachiko/clerk/releases/download/v#{version}/clerk_#{version}_linux_amd64.tar.gz"
    end
  end

  name "clerk"
  desc "CLI for managing AWS Parameter Store secrets with a terminal UI"
  homepage "https://github.com/yachiko/clerk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clerk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clerk"]
    end
  end

  # No zap stanza required
end
