# This file was generated by GoReleaser. DO NOT EDIT.
cask "clerk" do
  version "0.0.7"

  on_macos do
    on_arm do
      sha256 "d3d1f337611cfb5940d2de39b5d4d0a447765a8d096e5eaacc289f331a6e715d"
      url "https://github.com/yachiko/clerk/releases/download/v#{version}/clerk_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "18ac85718f6df7400a9f24ad91b3e88a1055ff956d5b9dde40f207edea91c7ab"
      url "https://github.com/yachiko/clerk/releases/download/v#{version}/clerk_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "44cacb82292ee3d1b1ce015ed3bbb314c5208c39d2988d3cbf9afb9b1a8e857c"
      url "https://github.com/yachiko/clerk/releases/download/v#{version}/clerk_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f32b03387afa79f6e23516ddaa8c423e14fd529c8c13b9458198aea2a417dd0e"
      url "https://github.com/yachiko/clerk/releases/download/v#{version}/clerk_#{version}_linux_amd64.tar.gz"
    end
  end

  name "clerk"
  desc "CLI for managing AWS Parameter Store secrets with a terminal UI"
  homepage "https://github.com/yachiko/clerk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clerk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clerk"]
    end
  end

  # No zap stanza required
end
