# This file was generated by GoReleaser. DO NOT EDIT.
cask "clerk" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "3f461eeb6dd1d6cb22fdb7325c2ea7a5ce78c19b83125458c6f92774e6b37ebb"
      url "https://github.com/yachiko/clerk/releases/download/v#{version}/clerk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "70198e8f243ac8113c1d53b55c802ded4b3f97474d629093ce48cc5c8661f903"
      url "https://github.com/yachiko/clerk/releases/download/v#{version}/clerk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1ce471228328040796aa28d8f319fc2f62c72bcacdf1105f1de8d59c339a0611"
      url "https://github.com/yachiko/clerk/releases/download/v#{version}/clerk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3fc1f807910373c620637af69c13f47d27d85a2ddd494385c2576cdd17efa34"
      url "https://github.com/yachiko/clerk/releases/download/v#{version}/clerk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "clerk"
  desc "CLI for managing AWS Parameter Store secrets with a terminal UI"
  homepage "https://github.com/yachiko/clerk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clerk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clerk"]
    end
  end

  # No zap stanza required

end
