# This file was generated by GoReleaser. DO NOT EDIT.
cask "fossor" do
  version "0.1.14"

  on_macos do
    on_arm do
      sha256 "8c5f5e4d91559f0623f6f699f67822970cf196f79655741961c737bd8cfdbc18"
      url "https://github.com/yachiko/fossor/releases/download/v#{version}/fossor_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bf03ccdc7be0df51da8ed7f46a24fb6d38d854aac4ceb45f58012d624b85469c"
      url "https://github.com/yachiko/fossor/releases/download/v#{version}/fossor_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "17c19d67fce5160d6762ba6363dce7232f187af0e4eff98c3dda854e1f319a15"
      url "https://github.com/yachiko/fossor/releases/download/v#{version}/fossor_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "92e169a40e4221076a463f131a24b6c68afa28018e3a2f8feb45762f70ae800f"
      url "https://github.com/yachiko/fossor/releases/download/v#{version}/fossor_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fossor"
  desc "Terminal UI for managing multiple Git repositories from a single screen"
  homepage "https://github.com/yachiko/fossor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fossor"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fossor"] if OS.mac?
  end

  # No zap stanza required
end
