# This file was generated by GoReleaser. DO NOT EDIT.
cask "fossor" do
  version "0.1.9"

  on_macos do
    on_intel do
      sha256 "5c579ac5f172be7fa8cc8525808b666fc2a362456d4083fb531b1466cdc99393"
      url "https://github.com/yachiko/fossor/releases/download/v#{version}/fossor_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a2f0d1622e851fca415f66e86179f09be9097278d6c2cf63ab0036fdc202242"
      url "https://github.com/yachiko/fossor/releases/download/v#{version}/fossor_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3add5658c0914a80fe9aaba73b1b2f3fb68f30db16aefd41c6f9faa1e2220e8f"
      url "https://github.com/yachiko/fossor/releases/download/v#{version}/fossor_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fcd8ef0d15a7b1d40db8d87c787d82416b3f8754e91aa734c27eb3607a6f8b06"
      url "https://github.com/yachiko/fossor/releases/download/v#{version}/fossor_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fossor"
  desc "Terminal UI for managing multiple Git repositories from a single screen"
  homepage "https://github.com/yachiko/fossor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fossor"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fossor"] if OS.mac?
  end

  # No zap stanza required

end
