# This file was generated by GoReleaser. DO NOT EDIT.
cask "fossor" do
  version "0.1.13"

  on_macos do
    on_arm do
      sha256 "bfef884e6429b67c0dc2f215a6808e966b0585b6ecb6446b2a7b95ad0ae823d0"
      url "https://github.com/yachiko/fossor/releases/download/v#{version}/fossor_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "842a264c52a8e01746fc8ecce3347e79bbd6911e4494acbf609793c11fb68ab2"
      url "https://github.com/yachiko/fossor/releases/download/v#{version}/fossor_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a94faf6ced9a37d2f3c94ede09b5195171c26def39022438ccabee2ed7e56fca"
      url "https://github.com/yachiko/fossor/releases/download/v#{version}/fossor_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a7863cda98bf1597fc5f273fda3fdcc28b3ce3cd74a9502a574277a2765c9209"
      url "https://github.com/yachiko/fossor/releases/download/v#{version}/fossor_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fossor"
  desc "Terminal UI for managing multiple Git repositories from a single screen"
  homepage "https://github.com/yachiko/fossor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fossor"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fossor"] if OS.mac?
  end

  # No zap stanza required
end
