# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clerk < Formula
  desc "CLI for managing AWS Parameter Store secrets with a terminal UI"
  homepage "https://github.com/yachiko/clerk"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yachiko/clerk/releases/download/v0.0.3/clerk_0.0.3_darwin_amd64.tar.gz"
      sha256 "55eae6e6bc132ca17dfcedf3ef7494d5c26c9ae276af39a012b04c6ea6fd3727"

      define_method(:install) do
        bin.install "clerk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yachiko/clerk/releases/download/v0.0.3/clerk_0.0.3_darwin_arm64.tar.gz"
      sha256 "37c4bf9bb5ee0e23103069ad1cb6499a214e7a40545194e5dd63aaa7b3f5b93f"

      define_method(:install) do
        bin.install "clerk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yachiko/clerk/releases/download/v0.0.3/clerk_0.0.3_linux_amd64.tar.gz"
      sha256 "7a3f45d7fc7591b22ed66bb0ae6f08dc8419315ac193f44cb08af400d1974c9a"
      define_method(:install) do
        bin.install "clerk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yachiko/clerk/releases/download/v0.0.3/clerk_0.0.3_linux_arm64.tar.gz"
      sha256 "7ca98cc0b337192b942d328b1c8b916a45ba96fa839e314f5171566121f9ff84"
      define_method(:install) do
        bin.install "clerk"
      end
    end
  end

  test do
    system "#{bin}/clerk", "--version"
  end
end
