# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fossor < Formula
  desc "Terminal UI for managing multiple Git repositories from a single screen"
  homepage "https://github.com/yachiko/fossor"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yachiko/fossor/releases/download/v0.1.5/fossor_0.1.5_darwin_amd64.tar.gz"
      sha256 "1800df7cb4ecd6e1c3a335cfd4126bf96c071cd0a597afc73b05529828e3ce77"

      define_method(:install) do
        bin.install "fossor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yachiko/fossor/releases/download/v0.1.5/fossor_0.1.5_darwin_arm64.tar.gz"
      sha256 "07302a1f619b9837cea2178e7b8a565ed4b449a319baf249555ea7467a4a4c63"

      define_method(:install) do
        bin.install "fossor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yachiko/fossor/releases/download/v0.1.5/fossor_0.1.5_linux_amd64.tar.gz"
      sha256 "5707a7de5892586509b150e8c7f88934cf6da24ae01966598613463a58b2f265"
      define_method(:install) do
        bin.install "fossor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yachiko/fossor/releases/download/v0.1.5/fossor_0.1.5_linux_arm64.tar.gz"
      sha256 "5073d0c2d7d2e8479f39751138125a8618cbf85f66817fc4050de459bb7b1c0c"
      define_method(:install) do
        bin.install "fossor"
      end
    end
  end

  test do
    system "#{bin}/fossor", "--version"
  end
end
